version: 0
metadata:
  name: taskcluster-lib-scopes
  description: 'Scopes library for taskcluster'
  owner: '{{ event.head.user.email }}'
  source: '{{ event.head.repo.url }}'
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
          - push
        branches:
          - master
    payload:
      maxRunTime: 3600
      image: 'node:8'
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo &&
          cd repo &&
          git config advice.detachedHead false &&
          git checkout {{event.head.sha}} &&
          yarn &&
          yarn lint &&
          yarn test
    metadata:
      name: taskcluster-lib-scopes test run
      description: Run library test suite
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
